### ISSUE TITLE
How to use this simulator in Linux ubuntu?

### ISSUE THREAD

**Issue by typo3ua** [eleurent/KestrelFPV#1]
Hi, there!

I found the simulator here for Linux but I do not found how install and how to use this simulator in Linux Ubuntu?

Do you have user guide or documentation for that?

Can you help understand how to use it in Linux?

Thanks!

**Comment by eleurent** [comment]
Hi!
You can directly download the [binaries](http://www.edouardleurent.com/binaries/KestrelFPV_Linux_x86_64.zip), unzip them, and then run the 32 bits (.x86) or 64 bits (.x86_64) binary.

Before running, check that you have execution permissions:
`chmod +x Kestrel_FPV.x86_64`

and then run:
`./Kestrel_FPV.x86_64`

**Comment by typo3ua** [comment]
I made it ... thank you so much! you are the best...

please, advise me what I need to take for driving this virtual drone, I mean, what manipulator I need?

**Comment by eleurent** [comment]
The simplest is to use a video game controller, such as an Xbox controller.

When I was learning, I personally used a Taranis X9D+ controller + usb cable, which has much more sensitive joysticks and controls (e.g. the throttle axis does not have a spring that pushes it back to neutral position), and it can later be used to control a real FPV drone. It is, however, much more expensive.

**Comment by typo3ua** [comment]
Thank you a lot!
